repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^go-runner/testdata/
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
    -   id: go-mod-tidy
    -   id: go-fmt
        exclude: ^go-runner/src/builder/template\.go$

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--all, --]
        files: ^go-runner/
        pass_filenames: false
        additional_dependencies: []
        entry: bash -c 'cd go-runner && cargo fmt --all'
        language: system

      - id: cargo-check
        args: [--all-targets]
        files: ^go-runner/
        pass_filenames: false
        additional_dependencies: []
        entry: bash -c 'cd go-runner && cargo check --all-targets'
        language: system

      - id: clippy
        args: [--all-targets, --, -D, warnings]
        files: ^go-runner/
        pass_filenames: false
        additional_dependencies: []
        entry: bash -c 'cd go-runner && cargo clippy --all-targets -- -D warnings'
        language: system
